name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-16.04
    name: Go build
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: "1.13.5"
      - run: |
          go build -mod=vendor -o operator github.com/oxyno-zeta/postgresql-operator/cmd/manager
          file operator
